### ISSUE TITLE
Messed positions

### ISSUE THREAD

**Issue by Liger0** [fieldOfView/Cura-SidebarGUIPlugin#1]
**Platform**
Windows 10 x64

**Actual Results**
The position of the words and graphics is messed up.

**Expected results**
Graphics should be kept in order.

**Additional Information**
![GUI](https://user-images.githubusercontent.com/20385116/55337931-e03ae480-549f-11e9-92a3-7ab6fa4ea02d.png)

**Comment by fieldOfView** [comment]
Thanks for the report. For the top-most issue, could you check if that also happens if you set the language in Cura to english? If not, I'll know where to look.

**Comment by Liger0** [comment]
Yeah, using the english Cura, the profile name tab appears correct.

**Comment by fieldOfView** [comment]
Ok, I'll fix that in a future version. I will also make sure the extruder tabs use the same positioning logic as the extruder selectors in the original top bar.

**Comment by fieldOfView** [comment]
Could you test this version:
http://files.fieldofview.com/cura/SidebarGUIPlugin-v6.0.0-2019-06-11T21_09_03Z.curapackage
Download the file, and drop it into a running Cura application window. Then restart Cura. It should work in both 4.0 and 4.1.

**Comment by Liger0** [comment]
It doesn't seem to work on 4.1. I installed it and the only difference I see is that now the sidebar on the right has a different weird position, which is out of alignment on the left by default, tho I can move it.

**Comment by fieldOfView** [comment]
There was a mistake in the original download. Can you download it again?

**Comment by Liger0** [comment]
Yeah, it works nice! The extruder icons are also correctly centered vertically with a correct spacing while on stock cura they are partially hidden, so it's even better using this plugin.

It would just be a nice addition to horizontally center the extruder tabs.
![sidebar plugin 4 1](https://user-images.githubusercontent.com/20385116/59360598-ace2c480-8d30-11e9-90cb-b5f51748ea15.png)

**Comment by fieldOfView** [comment]
> Yeah, it works nice!

👍 

> It would just be a nice addition to horizontally center the extruder tabs.

I don't agree.  Hardly anything is center-aligned in Cura, and I would like to keep it that way.

**Comment by Liger0** [comment]
> I don't agree. Hardly anything is center-aligned in Cura, and I would like to keep it that way.

But the extruder tabs are centered like here :confused:
https://user-images.githubusercontent.com/20385116/59359243-4b215b00-8d2e-11e9-8075-85fe1af34f0b.png

Btw, I just wanted to make sure the names of the materials not being perfectly vertically-centered but a bit up was intended behaviour, just to avoid it to be emphatized (in a wrong manner) on different resolutions/Screen scale factors.

**Comment by fieldOfView** [comment]
Yes, and that being the only center aligned things stands out like a sore thumb (IMHO). It will look even worse when the extruder icons are no longer in the center of the tab (because they are on the left of the material name). Finally, there's a technical challenge with having them center-aligned if you have - say - 4 extruders and the material names are long. Then you really want to have them left-aligned.
