### ISSUE TITLE
Perspective selector floating/collapsable

### ISSUE THREAD

**Issue by ScruffR** [fieldOfView/Cura-SidebarGUIPlugin#13]
It would be a nice feature if we could have this window collapsible, hidable and/or floating.
![image](https://user-images.githubusercontent.com/6604878/74711719-f622d680-5224-11ea-8ea0-7701ef48bb88.png)

As it is now, it takes up a lot of space with little extra benefit most of the time.

**Comment by fieldOfView** [comment]
I agree, and I was already planning to add this to a future version.

**Comment by fieldOfView** [comment]
Working on it here: https://github.com/fieldOfView/Cura-SidebarGUIPlugin/commit/4eda2c4e830ab93af1daffcd153dbb0ebd914dc4
