### ISSUE TITLE
Floating/Hiding the Settings Sidebar

### ISSUE THREAD

**Issue by GregValiant** [fieldOfView/Cura-SidebarGUIPlugin#16]
Cura 4.7, Win10 Home...
I am unable to either hide the bar or slide it out of the way.  Sometimes it's helpful to move or hide it so the zooming, panning, rotating can have more on-screen acreage.
Same issue with the smaller bar with the View icons.  Not hideable and it's seems fixed in place.

**Comment by fieldOfView** [comment]
This is implemented in the new version that is available in the Marketplace
