### ISSUE TITLE
Not compatible with Cura 4.8

### ISSUE THREAD

**Issue by 5axes** [fieldOfView/Cura-SidebarGUIPlugin#17]
Release of Cura limited in the plugin.json file 
    "minimum_cura_version": "4.0",
    "maximum_cura_version": "4.7",
Is it normal ?

**Comment by fieldOfView** [comment]
Yes, this is normal. The plugin does a lot of patching of qml files, and these patches may break Cura if the original qml files change. This is why each plugin release only works with the versions of Cura it is tested with.

The master branch has been made compatible with Cura 4.8, and is currently available as a beta version here:
https://community.ultimaker.com/topic/26014-sidebar-gui-for-cura-4/?do=findComment&comment=275194

I'll leave this issue open until the 4.8-compatible version is available in the Marketplace.

**Comment by Thisismydigitalself** [comment]
Same here. I understand this is fixed for the released version.
https://github.com/Ultimaker/Cura/issues/8664

**Comment by fieldOfView** [comment]
Did you read my comment just above?

**Comment by Thisismydigitalself** [comment]
Hi, I am not sure i understand what are my options now.
I do understand this is fixed now but not sure if i can test it with 4.8b or i need the master version. and, can i install plugs which are not yet listed in the marketplace without login in?

**Comment by fieldOfView** [comment]
> The master branch has been made compatible with Cura 4.8, **and is currently available as a beta version here**:
> https://community.ultimaker.com/topic/26014-sidebar-gui-for-cura-4/?do=findComment&comment=275194

**Comment by fieldOfView** [comment]
The 4.8-compatible version is now available from the Marketplace.

**Comment by Thisismydigitalself** [comment]
Perfect. 
Can't see myself using Cura without some of your must have plugins. thank you and keep up the good work.

![ice_screenshot_20201030-202734](https://user-images.githubusercontent.com/30949968/97743504-6db43f80-1aee-11eb-93a1-bfa5f5c87302.png)
