### ISSUE TITLE
not compatible with Cura 4.9

### ISSUE THREAD

**Issue by Sekisback** [fieldOfView/Cura-SidebarGUIPlugin#22]
try to run V 4.0.11-DEV on Cura 4.9 without success

**Comment by fieldOfView** [comment]
Please check the Marketplace for an update. The latest version is 4.1.1. I don't know where you got your 4.0.11-DEV version from, but it is at least a couple of months old now. The plugin needs to be updated for EVERY new minor version of Cura.

**Comment by Sekisback** [comment]
works with 4.1.1 sorry
