### ISSUE TITLE
v4.1.2 in Cura v4.10 causes UI to freeze/hang Win10

### ISSUE THREAD

**Issue by quadcom** [fieldOfView/Cura-SidebarGUIPlugin#25]
I drilled down to this causing Cura to become unresponsive and pretty much unusable.

Fairly new to printing and Cura so if there are any logs or anything I need to provide, let me know where I can find those.

**Comment by fieldOfView** [comment]
Do you have Powertoys installed? In that case, please look for an updated version of Powertoys.

**Comment by quadcom** [comment]
As a matter of fact I do have powertoys. 

Currently running the latest version, it was just updated the other day.

**Comment by fieldOfView** [comment]
See this issue: https://github.com/fieldOfView/Cura-SidebarGUIPlugin/issues/24
Try disabling FancyZones

**Comment by fieldOfView** [comment]
Did you get round to trying to disable FancyZones? Did that fix the issue?

**Comment by quadcom** [comment]
Sorry, no I haven't. I'm pretty new to printing so I don't do a whole lot
and I use fancy zones all the time.

In the future, If you've figured out a fix where they can live together,
I'll definitely test it out.

**Comment by fieldOfView** [comment]
I can't help you if you won't even temporarily turn the powertoy off to see if that indeed is the root of the problem. So I'll close this issue.
