### ISSUE TITLE
profile selector dropdown overlaps view selection in older Cura's

### ISSUE THREAD

**Issue by rburema** [fieldOfView/Cura-SidebarGUIPlugin#26]
Plugin version: 4.2.0 (as submitted)
Cura versions: (at least) 4.0.0, 4.1.0

See screenshots:
![sidebargui_dropdown_closed](https://user-images.githubusercontent.com/41987080/132339402-d3d37227-67e9-4593-be00-d079372f582c.png)
![sidebargui_dropdown_open](https://user-images.githubusercontent.com/41987080/132339502-63898e4e-b5cd-48b7-8c07-a7fec482d2dd.png)

**Comment by fieldOfView** [comment]
Thanks for the report (and the diligence in testing)!

**Comment by fieldOfView** [comment]
Turns out this has been an issue for a while. I'll fix it along with another minor issue with Cura 4.0-4.3 in plugin version 4.2.1.

**Comment by hoonu** [comment]
> Turns out this has been an issue for a while. I'll fix it along with another minor issue with Cura 4.0-4.3 in plugin version 4.2.1.

Any updates on this? I'm using this plugin with the Creality Slicer which is based on 4.8 and it overlays the marketplace button.
![image](https://user-images.githubusercontent.com/85466912/151449438-45edda79-3d14-4b93-9071-c80fdfd317d0.png)

**Comment by fieldOfView** [comment]
Yours looks like a different issue. I am going to need a less-cropped screenshot.

I don't officially support Creality Slicer. It is more than enough work to support many different versions of Ultimaker Cura. Since Creality does not disclose what they changed in Cura, I can not test my plugin(s) with their changes.

**Comment by fieldOfView** [comment]
I can't reproduce this anymore, so I am retiring this issue.
