### ISSUE TITLE
Version 4.11 incompatibility

### ISSUE THREAD

**Issue by InnoProd** [fieldOfView/Cura-SidebarGUIPlugin#27]
Just upgraded to Cura 4.11, and sidebar docking appears to be non-functional:

![SideBar GUI non-functional Screenshot 2021-09-08 104953](https://user-images.githubusercontent.com/89146406/132532495-f0b394dc-8d16-40ce-864d-d96ad5bd0051.jpg)
No hurry, just thought I'd mention it.

**Comment by Mitsuma** [comment]
If you want a quick workaround until fieldOfView brings out a proper update just go into:
"AppData\Roaming\cura\4.11\plugins\SidebarGUIPlugin\SidebarGUIPlugin"

Edit the plugin.json and change the "maximum_cura_version": "4.10" to 4.11

No warranty that 4.11 didnt change anything else that could break things, just in case somebody was as impatient as me.

**Comment by InnoProd** [comment]
Works perfectly, and such a simple fix too. Thanks for the help!

**Comment by fieldOfView** [comment]
Actually quite a bit changed in Cura 4.11, so I don't recommend this patch. I am close to releasing a version of the plugin for Cura 4.11, but before that is ready a development version that works in Cura 4.11 here: https://community.ultimaker.com/topic/26014-sidebar-gui-for-cura-4/page/5/?tab=comments#comment-294560

**Comment by fieldOfView** [comment]
Version 4.2.0 of the plugin is now available in the Marketplace, and is compatible with Cura 4.11.
