### ISSUE TITLE
Makes newer versions of Cura hang for multiple seconds.

### ISSUE THREAD

**Issue by AntiHeadshot** [fieldOfView/Cura-SidebarGUIPlugin#28]
Since Cura 4.9 this plugin makes it quite unusable.

When the window looses focus or you change the focus in the 3D-View Cura hangs for more than 5 seconds, every time.

Cura 4.8 runs just fine with this plugin.

**Comment by fieldOfView** [comment]
Do you have the "FancyZones" powertoy active? If so, this is a duplicate of https://github.com/fieldOfView/Cura-SidebarGUIPlugin/issues/24, and updating powertoys should fix it.

**Comment by AntiHeadshot** [comment]
🤦‍♂️ thank you very much. Running 0.2 still, just noticed it fails to update automatically.
