### ISSUE TITLE
Cura 4.1 Mac not working

### ISSUE THREAD

**Issue by medoh300** [fieldOfView/Cura-SidebarGUIPlugin#3]
the plugin doesnt seem to work as before on 4.1 on mac , probably because of the resize windows feature of cura 4.1

**Comment by fieldOfView** [comment]
The Sidebar GUI plugin is a plugin that will always need to be updated between versions. I do plan to update it for Cura 4.1, but I have not yet gotten round to it.

**Comment by skyhisi** [comment]
I've found it's not working on Windows 10 either, the Cura log file reports:
```
DEBUG - [MainThread] SidebarGUIPlugin.__matchVersion [48]: This version of the plugin is not compatible with this version of Cura. Please check for an update.
WARNING - [MainThread] SidebarGUIPlugin.register [23]: Plugin not loaded because of a version mismatch
ERROR - [MainThread] UM.PluginRegistry.loadPlugin [392]: Plugin SidebarGUIPlugin did not return any objects to register
```

**Comment by fieldOfView** [comment]
@skyhisi, you need to update the plugin. Please check the Marketplace.

**Comment by fieldOfView** [comment]
A test-version is available here:
http://files.fieldofview.com/cura/SidebarGUIPlugin-v6.0.0-2019-06-11T21_09_03Z.curapackage
Download the file, and drop it into a running Cura application window. Then restart Cura.

**Comment by 01msmr** [comment]
4.0.1 also doesn't work on 10.14.5 (Mojave).

**Comment by fieldOfView** [comment]
Sorry, I forgot to include a changed file. Could you try downloading the same file again? Thanks.
(This time I tested it myself...)

**Comment by 01msmr** [comment]
Thanks! Now it works.

**Comment by fieldOfView** [comment]
The posted version is now published in the Marketplace.

**Comment by 01msmr** [comment]
Great! works as expected.
