### ISSUE TITLE
Material selection is outside the dialog border and not accessible

### ISSUE THREAD

**Issue by GregValiant** [fieldOfView/Cura-SidebarGUIPlugin#32]
Hello A. Hoeben.  Nice place ya have here.  I was worried you might be getting bored so I brought you something to think about (although it may be that I have an early fix on the plugin and this has been taken care of).

I had my printer set up as a dual extruder and went to change materials on Extruder 2.  The drop down was OK.  I selected the manufacturer and the secondary selections appeared but the third set was off to the right and I couldn't get to them to actually change material.  Undocking the sidebar didn't help.  Here are two images with the sidebar docked and undocked.
The third image is from 4.13 where the primary choices went to the left and selecting the material worked.
(I used the Settings menu and successfully changed material.)

![Untitled](https://user-images.githubusercontent.com/64202104/166126517-f445eac4-199e-4ce4-a48f-51e09ef9d971.png)
![Untitled1](https://user-images.githubusercontent.com/64202104/166126518-d338bb62-e039-46e2-8e8a-114bd1320798.png)
![Untitled2](https://user-images.githubusercontent.com/64202104/166126519-9e241735-8944-41ec-a198-f3a2b9ee9b5d.png)

**Comment by fieldOfView** [comment]
This is a disadvantage of replacing native controls with "homebrewn stuff", the way Cura 5 does it. A similar problem happens without the sidebar gui plugin. I'm going to keep an eye out if this upstream patch fixes it:
https://github.com/Ultimaker/Cura/pull/11977

**Comment by GregValiant** [comment]
Thanks for looking at it.
I know the new release has been tedious for you and the Cura team but overall it looks like things are going well.  There has been a lot of interest.

**Comment by 5axes** [comment]
I just take advantage of this issue to ask if it would be possible to have also the color of the material as in the material parameters.
Example in version 4.13
![image](https://user-images.githubusercontent.com/11015345/166684964-8b2da657-b1ff-4dbd-a223-fcf5c0934f21.png)

In the Material settings

![image](https://user-images.githubusercontent.com/11015345/166685064-0fb450a7-35da-452b-88a9-6edc6a2f70f1.png)

**Comment by 5axes** [comment]
Tested with the "Official" release this issue is still present

**Comment by fieldOfView** [comment]
Could you test this prerelease?
https://github.com/fieldOfView/Cura-SidebarGUIPlugin/releases/tag/v4.3.0-DEV

**Comment by GregValiant** [comment]
That did it.  I'll close this.
