### ISSUE TITLE
Support for 5.0 beta?

### ISSUE THREAD

**Issue by ofek256** [fieldOfView/Cura-SidebarGUIPlugin#33]
Plugin refuses to launch on the new 5.0.0 Cura beta release, when can we expect an update / workaround? Thanks!

**Comment by fieldOfView** [comment]
See https://community.ultimaker.com/topic/40313-fieldofview-plugins-for-cura-50/

**Comment by ofek256** [comment]
OK, Thanks!

**Comment by fieldOfView** [comment]
The new version of the plugin is now available in the Marketplace
