### ISSUE TITLE
[enhancement] Material color in the material dropdownlist

### ISSUE THREAD

**Issue by 5axes** [fieldOfView/Cura-SidebarGUIPlugin#34]
On idea or cool feature will be the possibility to show the Material color in the dropdown material list :

Actual Interface

![image](https://user-images.githubusercontent.com/11015345/170004546-d16be161-fd7c-4a04-bc48-955ba0b189fe.png)

Visualisation of this material in the material manager of Cura

![image](https://user-images.githubusercontent.com/11015345/170004811-77cc197c-7b99-4d8a-a4c2-5d4dbe196ee1.png)

Proposed new Interface.

![image](https://user-images.githubusercontent.com/11015345/170005939-637f4f4b-4501-48d5-95d6-bac006bacc92.png)

**Comment by 5axes** [comment]
Cool , Thank's a lot @fieldOfView 
![image](https://user-images.githubusercontent.com/11015345/170734267-9d0bcee8-d014-4cc4-92a7-0e080277fdf2.png)

**Comment by fieldOfView** [comment]
I'll keep this open until the fixed version is available in the Marketplace.
