### ISSUE TITLE
Cura 5.3 Beta Missing Icons to access to the Reset and Save Function

### ISSUE THREAD

**Issue by 5axes** [fieldOfView/Cura-SidebarGUIPlugin#41]
In Cura 5.3 the UI have change and Now Reseting or Saving the modification into a project is done via some Icons on the Side of the profil : 
![image](https://user-images.githubusercontent.com/11015345/221233743-af60b2a2-32ed-437f-a04c-a6cc32cb56c6.png)

And Not in the Drop Down Menu as it was before. 

![image](https://user-images.githubusercontent.com/11015345/221234410-9417613d-0d59-4a86-87f9-224860d6823f.png)

So with the SideBarPlugin we don't have anymore acces to this function , We need to open the Profile Manager to Update Profil settings

**Comment by fieldOfView** [comment]
I fixed this by replacing the "star" icon with the two new icons.  That star icon should never have been a star icon in the first place.

**Comment by 5axes** [comment]
Thanks a lot .

Works in 5.3 Beta 2
![image](https://user-images.githubusercontent.com/11015345/222549378-1322a033-bb64-49db-9ebf-11d1f64dc739.png)

And 5.3 Alpha Xmas
![image](https://user-images.githubusercontent.com/11015345/222549750-769e8f21-2c50-47bf-9f8f-18725caa2b11.png)

**Comment by fieldOfView** [comment]
I'll close this when a new release is available in the Marketplace
