### ISSUE TITLE
Cura 5.2.1 Material selection from side bar not working. 

### ISSUE THREAD

**Issue by 3Dkat** [fieldOfView/Cura-SidebarGUIPlugin#42]
Cura 5.2.1 when trying to select material from the side bar, first two levels of the material menu are opening fine (manufacturer and material type), where color selection is no longer opening for neither custom nor default materials. Clicking on material type does not do anything.  In my case same story for single and dual extruder machines. Selection is available only from settings menu. Updated version of plug in works fine in version 4.13.0

Thank you

**Comment by fieldOfView** [comment]
Here's someone else affected by the bug:
https://community.ultimaker.com/topic/43098-problem-selecting-materials-in-cura-522

They confirmed that using the previous version of the plugin fixes the problem:
https://github.com/fieldOfView/Cura-SidebarGUIPlugin/releases/tag/v4.5.0
Download the .curapackage and drop it onto the Cura buildplate as if you were opening a model.

**Comment by 3Dkat** [comment]
> Here's someone else affected by the bug: https://community.ultimaker.com/topic/43098-problem-selecting-materials-in-cura-522

> 
> They confirmed that using the previous version of the plugin fixes the problem: https://github.com/fieldOfView/Cura-SidebarGUIPlugin/releases/tag/v4.5.0 Download the .curapackage and drop it onto the Cura buildplate as if you were opening a model.

Sorry was out for some time and missed a message. Well its the same issue as with Carbon in this thread https://community.ultimaker.com/topic/43098-problem-selecting-materials-in-cura-522
Same exact thing. Thank you for the solution, was thinking on rolling back, but decided to wait and here it is. If anything else is needed, I am here.

**Comment by fieldOfView** [comment]
Could you try if this release works for you in Cura 5.2?
https://github.com/fieldOfView/Cura-SidebarGUIPlugin/releases/tag/v4.6.1-DEV

**Comment by 3Dkat** [comment]
Works like a charm!  
Works with Cura 5.2. 3ed level menu appears, colors are showing.
Previously I said that its working fine in 4.13.0 but it was missing color dots next to the filament name. Still missing with this update. Menu works thou.

**Comment by fieldOfView** [comment]
The color dots will only work with Cura 5.0 and newer.

I'll mark this issue "fixed", but will keep it open until a new version of the plugin is available in the marketplace.

**Comment by 3Dkat** [comment]
Please hold! Just now I was slicing a model and I am getting an issue with slicing have failed. Never happened before.
This happens when I change initial layer setting form 0.2 to 0.3

**Comment by 3Dkat** [comment]
Here is what happens. I open previous project. Sometimes right from the start it gives me "unable to slice" even thought I printed it yesterday, and that was before I updated. I change the color of the filament and it slices. Next color does not. Those are my custom materials. Also when I change initial layer height it will not or will slice (honestly can not follow the pattern of events). 
![2023-03-16_22-41-27](https://user-images.githubusercontent.com/89118650/225708856-e91de39d-aae6-4f0f-8d19-7e55c7f7a50f.png)
![2023-03-16_22-42-03](https://user-images.githubusercontent.com/89118650/225708868-3af45f43-4cbe-4908-a419-6bf944f8a25f.png)
I also checked a possible issue with start up optimizer plug in. Uninstalled it, but issue still on hand.

**Comment by fieldOfView** [comment]
You can't blame _everything_ on my plugin ;-)

Just looking at the reported issues at the main Cura issue queue, there are lots of people suffering from the "slicing failed" problem:
https://github.com/Ultimaker/Cura/issues

If you move the model away from the mid-point of the Cura build plate the model will probably slice.
