### ISSUE TITLE
Long material names causes text to "break free" from tab

### ISSUE THREAD

**Issue by nallath** [fieldOfView/Cura-SidebarGUIPlugin#43]
When you select a material with a huge name, the variant gets pushed down to outside the tab. 

|![image](https://user-images.githubusercontent.com/3922611/233051859-1062bd28-5184-4707-979d-d6a51bccc34b.png)

When you try to push that notion to the extreme a bit, the variant is even pushed out to a nice vacation, never to be seen again:
![image](https://user-images.githubusercontent.com/3922611/233052291-0e59d6aa-7fd7-465b-975a-e5e2dfc827e3.png)

When collapsing the sidebar, the variant does show up again, but floating outside of the box:
![image](https://user-images.githubusercontent.com/3922611/233052733-9d545a2c-0c9a-44d3-a8f5-2bbe9b0bcc05.png)

**Comment by fieldOfView** [comment]
![I miss having an Andreea](https://www.monkeyuser.com/assets/images/2018/80-the-struggle.png)

Thanks for noticing this.
