### ISSUE TITLE
Cura 5.6 support

### ISSUE THREAD

**Issue by dxgldotorg** [fieldOfView/Cura-SidebarGUIPlugin#44]
Currently, the plugin fails to load in Cura 5.6.  Please update and upload to the Marketplace at your convenience.

**Comment by fieldOfView** [comment]
Please read this:
https://github.com/fieldOfView/Cura-SidebarGUIPlugin/issues/31

A prerelease is available. A fixed version is awaiting approval from Ultimaker. My hands are tied.

**Comment by erickwill** [comment]
> Please read this: #31
> 
> A prerelease is available. A fixed version is awaiting approval from Ultimaker. My hands are tied.

Is there any way to install it apart of ultimaker marketplace? I didn't find the proper version here in git..

**Comment by fieldOfView** [comment]
Sigh... https://github.com/fieldOfView/Cura-SidebarGUIPlugin/releases/tag/v4.6.4-DEV

Download the .curapackage, drag and drop it onto the Cura viewport as if you were opening a 3d model.
