### ISSUE TITLE
Cura (arch community) not loading

### ISSUE THREAD

**Issue by padok** [fieldOfView/Cura-SidebarGUIPlugin#5]
I installed Cura from the Arch Community Repository.

Start log: https://paste.kodi.tv/bololujezo.kodi

However, the GUI does not change after the extension is installed.
However, everything works when I use the appimage from the cura git.

**Comment by fieldOfView** [comment]
Like Ultimaker, I support only the AppImage.
There is nothing in the provided log that gives me any clue as to what's (not) happening.
