### ISSUE TITLE
Broken by Cura 4.2

### ISSUE THREAD

**Issue by 01msmr** [fieldOfView/Cura-SidebarGUIPlugin#6]

**Comment by fieldOfView** [comment]
A version of the Sidebar GUI plugin compatible with Cura 4.2 is awaiting review. In the mean time you can download it here: 

http://files.fieldofview.com/cura/SidebarGUIPlugin-v6.1.0-2019-07-18T12_34_52Z.curapackage

After downloading the curapackage, just drop it in the running Cura application window, and restart Cura.

**Comment by 01msmr** [comment]
Thanks.

Even works with the newer Cura version 4.2.1.

**Comment by fieldOfView** [comment]
The updated plugin is now also available from the Marketplace.
