### ISSUE TITLE
Legend box covers top of layer slider

### ISSUE THREAD

**Issue by zefiro34** [fieldOfView/Cura-SidebarGUIPlugin#8]
Hi.
In Cura 4.3 preview page the layer slider is covered by the legend box.
Is it possible to correct this?

**Comment by fieldOfView** [comment]
AFAIK, this only happens on small window sizes. Am I correct?

**Comment by fieldOfView** [comment]
Can you post a screenshot? The screen size does not tell me much; it also depends on the DPI setting and the screen resolution.

**Comment by zefiro34** [comment]
My resolution is 1366x768
![Anotação 2019-10-11 140251](https://user-images.githubusercontent.com/56434985/66655209-9479ac80-ec33-11e9-9c8e-5db774972b96.jpg)
